version: "3.0"
services:

  register:
    build: ./register
    ports:
      - 5024:5024
    environment:
      DB_HOST: "172.17.0.1"
      DB_PASS: "docker"

  users:
    build: ./users
    ports:
      - 5025:5025
    environment:
      DB_HOST: "172.17.0.1"
      DB_PASS: "docker"